context:
  colours:
   - hex: 7f1183
     variable: brand-primary
   - hex: b65e00
     variable: brand-secondary
   - hex: ffbf47
     variable: brand-theme
   - hex: ffffff
     variable: white
   - hex: f4f4f4
     variable: whitesmoke
   - hex: eeeeee
     variable: white-grey
   - hex: e9e8e8
     variable: ghost-gray
   - hex: d6d6d6
     variable: light-grey
   - hex: 706f6f
     variable: mid-grey
   - hex: 323232
     variable: dark-grey
   - hex: '000000'
     variable: black
   - hex: 80ab25
     variable: success
   - hex: ff0000
     variable: fail
   - hex: ecc202
     variable: highlight
   - hex: 00a5db
     variable: blue