context:
  long-text: List item with a much longer description or more content.
  short-text: List item.
  nested-text: Nested list item.	
variants:
- name: No Bullets
  context:
    long-text: List item with no bullet and a much longer description or more content.
    short-text: List item with no bullet.
    modifier: no-bullet